config/routes.rb
KForum::Application.routes.draw do

  ActiveAdmin.routes(self)

  resources :posts do
    resources :comments
  end

  resources :topics

  resources :forums

  devise_for :users do
     resources :posts
     resources :comments
  end

  match 'tagged' => 'posts#tagged', :as => 'tagged'

  resources :comments
  
  root :to => 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/users/:id', to: 'users#show'
  
  mount Refinery::Core::Engine, :at => '/static'
  
  

  match '*a', :to => 'application#routing_error'
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :description, :name, :forum_id
  has_many :topics, :dependent => :destroy
  
  def most_recent_post  
    topic = Topic.first(:order => 'last_post_at DESC', :conditions => ['forum_id = ?', self.id])  
    return topic  
  end

  validates_uniqueness_of :name
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :admin_required, :except => [:index, :show]  
  
  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forums }
    end
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @forum = Forum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/new
  # GET /forums/new.json
  def new
    @forum = Forum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to forums_path, notice: 'Forum was successfully created.' }
        format.json { render json: forums_path, status: :created, location: @forum }
      else
        format.html { render action: "new" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forums/1
  # PUT /forums/1.json
  def update
    @forum = Forum.find(params[:id])

    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to forums_path, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to forums_url , notice: 'Forum was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %><br />
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows=>"5" ,:cols=> "80", :style => "width: 500px;" %><br />
  </div> <br />
  <div class="actions" >
    <%= f.submit :class => "btn btn-primary", :style =>"color:white" %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<% full_title "Editing forum" %>
<h2 class="pull-left">Editing forum</h2><br /><br /><br />

<%= render 'form' %>

app/views/forums/index.html.erb
<% provide(:title, "Forums") %>
<div style="background-color: #131517; 
			padding: 10px 10px 40px; 
			color: white" >
	<h4 class="pull-left" style="font-size: 25px">Discussion Forums</h4>
</div>
<table class="table table-striped table-bordered" style="background-color: rgba(40, 40, 40, 0.9);color: white">  
  <tr style="background-color: #131517">
    <th width="70%">Forum</th>  
    <th width="30%">Last Post</th>
    <th></th>
    <th></th>  
  </tr>  
  <% for forum in @forums %>  
    <tr>  
      <td><h4><%= link_to h(forum.name), forum_path(forum.id) %></h4>  
        <small><%= forum.topics.count %> topics</small><br />  
        <%=h forum.description %>
      </td>  
      <td>
      	<% if forum.most_recent_post %>
      		<% if !forum.most_recent_post.user.nil? %>
      			<%= distance_of_time_in_words_to_now forum.most_recent_post.last_post_at %> ago by <%= link_to forum.most_recent_post.user.username, "/users/#{forum.most_recent_post.last_poster_id}" %>
      		<% else %>
      			<%= distance_of_time_in_words_to_now forum.most_recent_post.last_post_at %> ago by <i>Anonymous</i>
      		<% end %>	
      	<% else %>no posts<% end %>
      </td>  
      <% if current_user.admin? %>
      	<td><%= link_to "Edit", edit_forum_path(forum) %></td>
      <% else %>
      	<td></td>
      <% end %>  
      <% if current_user.admin? %>
      	<td><%= link_to "Delete", forum, :confirm => 'Are you sure?', :method => :delete %></td>
      <% else %>
      	<td></td>
      <% end %>  
    </tr>  
  <% end %>  
</table>

<% if current_user.admin? %>
<br />  
<p><%= link_to "New Forum", new_forum_path , :class => "btn btn-large btn-primary", :style =>"color:white" %></p>
<% end %>

app/views/forums/new.html.erb
<% full_title "New forum" %>
<h2 class="pull-left">New forum</h2><br /><br /><br />

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<% provide(:title, "Forums") %>

<div style="height:100%;  
			background-color: #131517; 
			padding: 10px 10px 40px; 
			color: white" >
			
			<h4 class="pull-left" style="font-size: 25px">Forum: "<%= @forum.name %>"</h4>
</div><br />

<table class="table table-striped table-bordered" style="background-color: rgba(40, 40, 40, 0.9); color: white">  
  <tr style="background-color: #131517">  
    <th width="60%">Topic Title</th>  
    <th width="10%">Total Posts</th>  
    <th width="30%">Last Post</th>
    <th></th>
    <th></th>  
  </tr>  
  <% for topic in @forum.topics %>  
    <tr>  
      <td><%= link_to h(topic.name), topic_path(topic.id) %>  
      <td><%= topic.posts.count %></td>  
      <td class="right">
      	<% if !topic.user.nil? %>
      		<%= distance_of_time_in_words_to_now topic.last_post_at %> ago by <%= link_to topic.user.username, "/users/#{topic.last_poster_id}" %>
      	<% else %>
      		<%= distance_of_time_in_words_to_now topic.last_post_at %> ago by <i>Anonymous</i>
      	<% end %>	
      </td>
     
     <% if admin_or_owner?(topic.user_id)  %>
     	<td><%= link_to "Edit",edit_topic_path(topic.id) %></td>
     <% else %>
     	<td></td>
     <% end %>
     <% if current_user.admin? %>
     	<td><%= link_to "Delete", topic, :confirm => 'Are you sure?', :method => :delete %></td>
     <% else %>
     	<td></td>
     <% end %>
    </tr>  
  <% end %>  
</table><br />  
<p><%= link_to "New Topic", "/topics/new?forum_id=#{@forum.id}" , :class => "btn btn-large btn-primary", :style =>"color:white" %></p>