config/routes.rb
KForum::Application.routes.draw do

  ActiveAdmin.routes(self)

  resources :posts do
    resources :comments
  end

  resources :topics

  resources :forums

  devise_for :users do
     resources :posts
     resources :comments
  end

  match 'tagged' => 'posts#tagged', :as => 'tagged'

  resources :comments
  
  root :to => 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/users/:id', to: 'users#show'
  
  mount Refinery::Core::Engine, :at => '/static'
  
  

  match '*a', :to => 'application#routing_error'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :last_post_at, :last_poster_id, :name, :user_id, :forum_id
  belongs_to :forum
  belongs_to :user
  has_many :posts, :dependent => :destroy
  validates_uniqueness_of :name
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  #before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :authenticate_user! 
  #before_filter :authenticate_user!, :only => :destroy
  
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    
    params[:topic][:last_poster_id] = current_user.id
    params[:topic][:last_post_at] = Time.now
    params[:topic][:user_id] = current_user.id

    @topic = Topic.new(:name => params[:topic][:name],
      :last_poster_id => params[:topic][:last_poster_id],
      :last_post_at => params[:topic][:last_post_at],
      :forum_id => params[:forum_id],
      :user_id => params[:topic][:user_id])
    
    respond_to do |format|
      if @topic.save
        format.html { redirect_to "/forums/#{@topic.forum_id}", notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to forum_url(@topic.forum_id), notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    forum_id = @topic.forum_id
    @topic.destroy

    respond_to do |format|
      format.html {  redirect_to forum_url(forum_id) , notice: 'Topic was successfully deleted.'}
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:forum_id] %>
  	<input type="hidden" id="forum_forum_id" name="forum_id" value="<%= params[:forum_id] %>" />
  <% end %>
    
  <div class="field">
    <%= f.label :name , :style => "color: white"%>
    <%= f.text_field :name %><br />
  </div><br />
  <div class="actions">
    <%= f.submit :class => "btn btn-large btn-primary", :style =>"color:white" %>
    <%= link_to "Cancel" , :back, :class => "btn btn-large btn-primary", :style =>"color:white"  %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<% full_title "Editing topic" %>
<div style="width: 350px; background-color: rgba(40, 40, 40, 0.9);padding: 20px; color: white">
	<h2 class="pull-left">Editing topic</h2><br /><br /><br />
	<%= render 'form' %>
</div>

app/views/topics/index.html.erb
<h1>Listing topics</h1>
<h2> <%= params %> </h2>
<table>
  <tr>
    <th>Name</th>
    <th>Last poster</th>
    <th>Last post at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.name %></td>
    <td><%= topic.last_poster_id %></td>
    <td><%= topic.last_post_at %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', "/topics/new?forum_id=#{@forum.id}" , :class => "btn btn-primary", :style =>"color:white" %>

app/views/topics/new.html.erb
<% full_title "New topic" %>
<div style="width: 350px; background-color: rgba(40, 40, 40, 0.9);padding: 20px; color: white">
	<h2 class="pull-left">New topic</h2><br /><br /><br />
	<%= render 'form' %>
</div>

app/views/topics/show.html.erb
<% provide(:title, @topic.name) %>
<% @forumHash = find_forumName_by_topicId(params[:id]) %>
<div style="height:100%;  
			background-color: #131517; 
			padding: 10px 10px 40px; 
			color: white" >
		<h2 class="pull-left"><%= link_to @forumHash[:forum], forum_path(:id => @forumHash[:forum_id] ) %> >> <%= @topic.name %></h2>
</div><br />

<% if @topic.posts.count > 0 %>
	<%@outer_index=1%>
	<div >
	<% for post in @topic.posts %>
	<div class="well well-large" style="background-color: rgb(40, 40, 40); border-radius: 6px 6px 6px 6px;">
	    <% @post = post %>
		  		<div class="row" style="color: white">
		  			<!--<div class="span2" style="width: 110px">
		  				<%= link_to gravatar_for(post.user), post.user.username %>
		  			</div> -->
	       			<div class="span12" style="padding-left: 20px"><%= raw(post.content) %></div>
	       			
	       			<div class="span12 pull-right" style="border-radius: 8px 8px 8px 8px; margin-left: 20px"><i class="icon-tags icon-white"></i><% @post.tags.any? %>
				        <% @post.tags.each do |tag| %>				        
				         <div class="box-tag"> <%= link_to tag.name, tagged_url(:tag => tag.name) %></div>
					<% end %>
					</div>
	       			
	       			<br /><br />
	       			<div class="span12"> 
	       				   <p class="posted-at pull-right">–Posted  <abbr class="timeago" title="<%= (post.created_at).getutc.iso8601 %>"></abbr> 
	       						  by <a href="/users/<%= post.user_id %>" > <%= find_user(post.user_id).username %>  
	       						</a>
	       					</p>
	       			</div>
	       		</div>
	        	<div class="well well-small" style="background-color: rgba(40, 40, 40, 0.9) ">
				<div class="tabbable tabs-left">
				<% @all_comments = post.comment_threads %>
		        <% if @all_comments %>
		        	<ul class="nav nav-tabs">
		        		<% @i = 1 %>
						<% for c in @all_comments %>
							<li id="li-tab<%=@i%><%=@outer_index%>">
								<a href="#tab<%=@i%><%=@outer_index%>" data-toggle="tab"><i class="icon-comment icon-white"></i></a>
							</li>
					   		<% @i = @i + 1 %>
						<% end %>
					</ul>
					<div class="tab-content">
						<% @i = 1 %>
						<% for c in @all_comments %>							
					   		<% @user = find_user(c.user_id) %>
					   		<div class="tab-pane" id="tab<%=@i%><%=@outer_index%>">
					     	 <pre>
							    <p class="posted-details"><%= raw(c.body) %></p>
							    <p class="posted-at">–Posted  <abbr class="timeago" title="<%= (c.created_at).getutc.iso8601 %>"></abbr> by <a href="/users/<%= @user.id %>"><%= @user.username %> </a></p>
						     </pre>
							 <% @i = @i + 1 %>
							 <div class="pull-right"><% if owner?(c.user_id) %>
						  		<i class="icon-edit icon-white"></i><%= link_to " Edit Comment", edit_comment_path(:id => c.id, :post_id => c.commentable_id) %> |
						  	 <% end %>
						  	 <% if admin_or_owner?(c.user_id) %>
						  		<i class="icon-trash icon-white"></i><%= link_to " Delete Comment", c , :params => {:id => c.id, :post_id => c.commentable_id}, :method =>:delete, :confirm => "Are you sure?" %>
						     <% end %></div>
					    	 
				     		</div>
					    	
						<% end %>
					</div>
			    <% end %>
			    </div> <!-- end of tabbable tabs-left --> 
			    </div> <!-- end of well small -->
			    <div><script language="javascript"> this.document.getElementById("li-tab1<%=@outer_index%>").setAttribute("class", "active");</script></div>
			    <div><script language="javascript"> this.document.getElementById("tab1<%=@outer_index%>").setAttribute("class", "tab-pane active");</script></div>
				
					
		  
		 <p>
		 <!-- <a href="/comments/new?post_id=<%= post.id %>" title="Comment" 
		   onclick="Modalbox.show(this.href, {title: this.title, width: 800}); return false;">
		   Comment</a> -->
		  <% if user_signed_in? %>
		     <i class="icon-pencil icon-white"></i><%= link_to " Comment on post", "/comments/new?post_id=#{post.id}"%> 
		  <% end %>
	 	  <% if admin_or_owner?(post.user_id) %>
		  	| <i class="icon-edit icon-white"></i><%= link_to " Edit Post", edit_post_path(post) %>
		  <% end %>
		  <% if admin_or_owner?(post.user_id) %>
		  	| <i class="icon-trash icon-white"></i><%= link_to " Delete Post", post, :method =>:delete,:confirm => "Are you sure?" %>
		  <% end %>	
		 </p>
	 </div>	 <!-- end of well large -->	
     <%@outer_index = @outer_index + 1 %>
	 <% end %>
	 </div>	
	 

	 
	 <% if user_signed_in? %>
	 	<%= link_to "Add New Post", "#{new_post_path}?topic_id=#{@topic.id}" , :class => "btn btn-large btn-primary", :style =>"color:white" %>
	 	<%= link_to "Go Back" , "/forums/#{@topic.forum_id}", :class => "btn btn-large btn-primary", :style =>"color:white"  %>
	 <% end %>
	 	 
<% else %>
	<%= link_to "New Post", "/posts/new?topic_id=#{@topic.id}" , :class => "btn btn-large btn-primary", :style =>"color:white"  %>
<% end %>