config/routes.rb
KForum::Application.routes.draw do

  ActiveAdmin.routes(self)

  resources :posts do
    resources :comments
  end

  resources :topics

  resources :forums

  devise_for :users do
     resources :posts
     resources :comments
  end

  match 'tagged' => 'posts#tagged', :as => 'tagged'

  resources :comments
  
  root :to => 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/users/:id', to: 'users#show'
  
  mount Refinery::Core::Engine, :at => '/static'
  
  

  match '*a', :to => 'application#routing_error'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :user_id, :forum_id, :topic_id, :tag_list
  belongs_to :topic
  belongs_to :user
  has_many :comments
  acts_as_commentable
  acts_as_taggable_on :tags
  
  #searchable do
  #  text :content
  #end
  
  def self.search_by_content(search, page)
    
    if connection.adapter_name == 'PostgreSQL'
        paginate :per_page => 5, :page => page,
           :conditions => ["(content ILIKE :cond1) OR (content ILIKE :cond2) OR (content ILIKE :cond3) OR (content ILIKE :cond4)
                OR (content ILIKE :cond5) OR (content ILIKE :cond6)",
             { :cond1 => "%#{search}%", :cond2 => "%#{search.gsub(/\s+/, "")}%",
             :cond3 => "%#{search.singularize}%", :cond4 => "%#{search.singularize.gsub(/\s+/, "")}%",
             :cond5 => "%#{search.pluralize}%", :cond6 => "%#{search.pluralize.gsub(/\s+/, "")}%"
              }
             ]
    else
        paginate :per_page => 5, :page => page,
           :conditions => ["(content LIKE :cond1) OR (content LIKE :cond2) OR (content LIKE :cond3) OR (content LIKE :cond4)
                OR (content LIKE :cond5) OR (content LIKE :cond6)",
             { :cond1 => "%#{search}%", :cond2 => "%#{search.gsub(/\s+/, "")}%",
             :cond3 => "%#{search.singularize}%", :cond4 => "%#{search.singularize.gsub(/\s+/, "")}%",
             :cond5 => "%#{search.pluralize}%", :cond6 => "%#{search.pluralize.gsub(/\s+/, "")}%"
              }
             ]
      end

  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :authenticate_user!
  
  
  # GET /posts
  # GET /posts.json
  def index
    # The below is for having solr work with your app.
    #
    # @search = Post.solr_search do
    #  fulltext params[:search]
    #  paginate :page => params[:page] || 1, :per_page => 4
    # end
    # @posts = @search.results
    #
    #
    
     
   @posts = Post.search_by_content(params[:search], params[:page])
   @tags = Post.tag_counts_on(:tags)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end



  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @topic = Topic.find(params[:topic_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])  
    admin_or_owner_required(@post.user.id)
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(:content => params[:post][:content], 
    :topic_id => params[:post][:topic_id], 
    :user_id => current_user.id,:tag_list => params[:post][:tag_list])  
    
    respond_to do |format|
      if @post.save
        @topic = Topic.find(@post.topic_id)  
        @topic.update_attributes(:last_poster_id => current_user.id, :last_post_at => Time.now)  
        format.html { redirect_to "/topics/#{@post.topic_id}" , notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])  
    admin_or_owner_required(@post.user.id) 

    respond_to do |format|
      if @post.update_attributes(params[:post])
        @topic = Topic.find(@post.topic_id)  
        @topic.update_attributes(:last_poster_id => current_user.id, :last_post_at => Time.now)  
    
        format.html { redirect_to @topic, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    topic_id = @post.topic_id  
    admin_or_owner_required(@post.user.id)
     
    @post.destroy

    respond_to do |format|
      format.html { redirect_to topic_url(topic_id)  }
      format.json { head :no_content }
    end
  end
  
  
  def tagged
    if params[:tag].present? 
      puts "params tag present"
      @posts = Post.tagged_with(params[:tag])
      puts  @posts.count
    else 
      @posts = Post.postall
    end  
  end
  

end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
  
  def show_tag_cloud
     options = {:page => params[:page], :per_page => 20} # any search/pagination conditions go here
     @tags = Post.tag_counts_on(:tags)
     klass = Post
     klass = klass.tagged_with(@keyword) if (@keyword = params[:tags]).present?
     @posts = klass.paginate( options )
   end
   
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

	<div disabled="true">
		<script type="text/javascript" >
		   $(document).ready(function() {
		      $("textarea").markItUp(mySettings);
		   });
		</script>
	</div>
	
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:topic_id] %>
  	<input type="hidden" id="topic_forum_id" name="post[topic_id]" value="<%= params[:topic_id] %>" />
  <% end %>
    
  <div class="field">
    <%= f.text_area :content,:cols=>"60", :rows=>"8"  %>
  </div>
   	<div><%= f.label :tags %>
	<%= f.text_field :tag_list %>
	</div>

  <div class="actions">
    <%= f.submit  :class => "btn btn-large btn-primary", :style =>"color:white" %>
    <%= link_to "Cancel" , :back, :class => "btn btn-large btn-primary", :style =>"color:white"  %>
  </div>
<% end %>

app/views/posts/_post_stream.html.erb
<% @post_activity_stream.each do |postitem| %>
	<% find_TopicName_by_Id(postitem.topic_id) %>
	<% @user = find_user(postitem.user_id) %>
	<blockquote style="padding: 0px;font-size: 10px; font-family: 'Paprika', cursive; color: white ">
		<p style=" font-size: 12px; font-family: 'Paprika', cursive;color: white ; word-wrap:break-word">
			<%= link_to raw(truncate(postitem.content)), topic_path(@topic.id) %></p>	
		<div class="pull-right">
			<div><%= distance_of_time_in_words_to_now postitem.created_at %> ago by </div>
			<div style=" font-size: 10px; font-family: 'Paprika', cursive;color: white ;">
				<%= gravatar(@user.username ,@user.email, "width: 20px; height: 20px; padding-right:2px") %></div>
			<div><%= link_to @user.username , "/users/#{postitem.user_id}" %></div>
		</div>	
	</blockquote>
 	<br />
 	<br />
<% end %>

app/views/posts/_tagcloud.html.erb
    <div style="background-color: #131517;padding: 10px; color: white;" >
			
	<% show_tag_cloud %>
	<span>
    <% @tags.sort_by(&:count).reverse.each do |k| %>
      <% url_opts = {:action => "tagged", :controller => "posts"}
         link_name = "#{k.name} (#{k.count})"
      %>
      <% if @tag == k.name %>
        <%= link_to link_name, url_opts.merge(:tag => nil), 
        	:class => "tag current_tag", :title => "Click again to see all", :style => "margin:5px; display: inline-block;" %>
      <% else %>
        <%= link_to link_name,  url_opts.merge(:tag => k.name), 
        	:class => "tag", :title => "Click to filter by #{k.name}" , :style => "margin:5px; display: inline-block;"%>
      <% end %>
      
    <% end %>
    </span>
    </div>

app/views/posts/edit.html.erb
<% full_title "Edit Post" %>
<div style="width: 700px; background-color: rgba(40, 40, 40, 0.9);padding: 20px; color: white">
	<h2 class="pull-left">Edit Post</h2><br /><br /><br />
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% if params[:search] != nil && params[:search] != "" %>
	<% provide(:title, "Listing Posts with Keyword : " + params[:search] + "...") %>
	<div style="height:100%;  
			background-color: rgba(40, 40, 40, 0.9); 
			padding: 10px 10px 40px; 
			color: white" >
			
			<h4 class="pull-left" style="font-size: 25px;">All Posts with Keyword : <%=params[:search]%></h4>
	</div>
<% else %>
	<% provide(:title, "Listing all Posts...") %>
	<div style="height:100%;  
			background-color: rgba(40, 40, 40, 0.9); 
			padding: 10px 10px 40px; 
			color: white" >
			
			<h4 class="pull-left" style="font-size: 25px;">No KeyWord supplied for search, Listing all Posts...</h4>
	</div>
<% end %>

<% if @posts.count > 0 %>
	<%= will_paginate @posts, 
				:style =>"height:100%; background-color: rgba(40, 40, 40, 0.9) ; color: white; padding:10px; border-radius: 6px 6px 6px 6px;" %>
	<br />

	<% @outer_index=1 %>
	<div >
	<% for post in @posts %>
	
		<% @forumHash = find_forumName_by_topicId(post.topic_id) %>
		<% @topicHash = find_TopicName_by_Id(post.topic_id) %>
		
		<div style="height:100%;  
					background-color: #131517; 
					padding: 5px 5px 20px; 
					color: white; border-radius: 6px 6px 6px 6px;" >
				<h4 class="pull-left"><%= link_to @forumHash[:forum], forum_path(:id => @forumHash[:forum_id] ) %> >> 
					<%= link_to @topicHash[:topic_name], topic_path(:id => @topicHash[:topic_id] ) %></h4>
		</div>
		<div class="well well-large" style="background-color: rgb(40, 40, 40); border-radius: 6px 6px 6px 6px;">
	    <% @post = post %>
		  		<div class="row" style="color: white">
		  			<!--<div class="span2" style="width: 110px">
		  				<%= link_to gravatar_for(post.user), post.user.username %>
		  			</div> -->
	       			<p class="span12" style="padding-left: 20px"><%= raw(post.content) %></p>
	       			
	       			<div class="span12 pull-right" style="border-radius: 8px 8px 8px 8px; margin-left: 20px"><i class="icon-tags icon-white"></i><% @post.tags.any? %>
				        <% @post.tags.each do |tag| %>				        
				         <div class="box-tag"> <%= link_to tag.name, tagged_url(:tag => tag.name) %></div>
					<% end %>
					</div>
	       			
	       			<br /><br />
	       			<div class="span12"> 
	       				   <p class="posted-at pull-right">–Posted  <abbr class="timeago" title="<%= (post.created_at).getutc.iso8601 %>"></abbr> 
	       						  by <a href="/users/<%= post.user_id %>" > <%= find_user(post.user_id).username %>  
	       						</a>
	       					</p>
	       			</div>
	       		</div>
	        	<div class="well well-small" style="background-color: rgba(40, 40, 40, 0.9) ">
				<div class="tabbable tabs-left">
				<% @all_comments = post.comment_threads %>
		        <% if @all_comments %>
		        	<ul class="nav nav-tabs">
		        		<% @i = 1 %>
						<% for c in @all_comments %>
							<li id="li-tab<%=@i%><%=@outer_index%>">
								<a href="#tab<%=@i%><%=@outer_index%>" data-toggle="tab"><i class="icon-comment icon-white"></i></a>
							</li>
					   		<% @i = @i + 1 %>
						<% end %>
					</ul>
					<div class="tab-content">
						<% @i = 1 %>
						<% for c in @all_comments %>							
					   		<% @user = find_user(c.user_id) %>
					   		<div class="tab-pane" id="tab<%=@i%><%=@outer_index%>">
					     	 <pre>
							    <p class="posted-details"><%= raw(c.body) %></p>
							    <p class="posted-at">–Posted  <abbr class="timeago" title="<%= (c.created_at).getutc.iso8601 %>"></abbr> by <a href="/users/<%= @user.id %>"><%= @user.username %> </a></p>
						     </pre>
							 <% @i = @i + 1 %>
							 <div class="pull-right"><% if owner?(c.user_id) %>
						  		<i class="icon-edit icon-white"></i><%= link_to " Edit Comment", edit_comment_path(:id => c.id, :post_id => c.commentable_id) %> |
						  	 <% end %>
						  	 <% if admin_or_owner?(c.user_id) %>
						  		<i class="icon-trash icon-white"></i><%= link_to " Delete Comment", c , :params => {:id => c.id, :post_id => c.commentable_id}, :method =>:delete, :confirm => "Are you sure?" %>
						     <% end %></div>
					    	 
				     		</div>
					    	
						<% end %>
					</div>
			    <% end %>
			    </div> <!-- end of tabbable tabs-left --> 
			    </div> <!-- end of well small -->
			    <div><script language="javascript"> this.document.getElementById("li-tab1<%=@outer_index%>").setAttribute("class", "active");</script></div>
			    <div><script language="javascript"> this.document.getElementById("tab1<%=@outer_index%>").setAttribute("class", "tab-pane active");</script></div>
				
					
		  
		 <p>
		 <!-- <a href="/comments/new?post_id=<%= post.id %>" title="Comment" 
		   onclick="Modalbox.show(this.href, {title: this.title, width: 800}); return false;">
		   Comment</a> -->
		  <% if user_signed_in? %>
		     <i class="icon-pencil icon-white"></i><%= link_to " Comment on post", "/comments/new?post_id=#{post.id}"%> 
		  <% end %>
	 	  <% if admin_or_owner?(post.user_id) %>
		  	| <i class="icon-edit icon-white"></i><%= link_to " Edit Post", edit_post_path(post) %>
		  <% end %>
		  <% if admin_or_owner?(post.user_id) %>
		  	| <i class="icon-trash icon-white"></i><%= link_to " Delete Post", post, :method =>:delete,:confirm => "Are you sure?" %>
		  <% end %>	
		 </p>
	 </div>	 <!-- end of well large -->	
     <%@outer_index = @outer_index + 1 %>
	 <% end %>
	 </div>
	 	 
<% else %>
	<div style="height:100%; min-height: 450px; 
					background-color: rgba(40, 40, 40, 0.9); 
					padding: 10px 10px 40px; 
					color: white" >
				<h4 class="pull-left">No Post Found, Please try with another keyword again or search from the tags below...</h4>
				<br /><br />
				<%= render :partial => "posts/tagcloud"  %>
				<br /><br />		
	</div><br />
<% end %>

<%= will_paginate @posts, 
				:style =>"height:100%; background-color:rgba(40, 40, 40, 0.9) ; color: white; padding:10px; border-radius: 6px 6px 6px 6px;" %>
	


<!--
<h1>Listing posts</h1>
<h2> <%= params %></h2>
<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= form_tag posts_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
<% end %> -->

app/views/posts/new.html.erb
<% full_title "New Post" %>
<div style="width: 700px; background-color: rgba(40, 40, 40, 0.9);padding: 20px;color: white">
	<h4 class="pull-left">You are Posting on Topic:</h4><br /><br />
	<%= raw(@topic.name) %><br /><br />
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<p>
  <b>Post Content:</b>
  <%= @post.content %>
</p>

<%= link_to 'Back', posts_path %>

app/views/posts/tagged.html.erb
<% provide(:title, params[:tag]) %>
<div style="height:100%;  
			background-color: #131517; 
			padding: 10px 10px 30px; 
			color: white" >
			<h4 class="pull-left" style="font-size: 25px">All posts tagged with: &nbsp;&nbsp;&nbsp;<%= params[:tag] %></h4>
</div><br />
<% provide(:title, "Tag: #{params[:tag]}" ) %>

<!-- <div id="tag_cloud">
  <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tagged_url(:tag => tag.name), class: css_class %>
  <% end %>
</div> -->


	<% @outer_index=1 %>
	
	<% @posts.each do |post| %>
	<div class="well well-large" style="background-color: rgb(40, 40, 40); border-radius: 6px 6px 6px 6px;">
	    <% @post = post %>
		  		<div class="row">
		  			<!--<div class="span2" style="width: 110px">
		  				<%= link_to gravatar_for(post.user), post.user.username %>
		  			</div> -->
	       			<div class="span12" style="padding-left: 20px; color: white"><%= raw(post.content) %></div>
	       			
	       			<div class="span12 pull-right" style="border-radius: 8px 8px 8px 8px; margin-left: 20px"><i class="icon-tags icon-white"></i><% @post.tags.any? %>
				        <% @post.tags.each do |tag| %>				        
				         <div class="box-tag" style="float: left; text-align: left;border-radius: 8px 8px 8px 8px;"> <%= link_to tag.name, tagged_url(:tag => tag.name) %></div>
					<% end %>
					</div>
	       			
	       			<br /><br />
	       			<div class="span12"> 
	       				   <p class="posted-at pull-right">–Posted  <abbr class="timeago" title="<%= (post.created_at).getutc.iso8601 %>"></abbr> 
	       						  by <a href="/users/<%=post.user.id%>" > <%= find_user(post.user_id).username %>  
	       						</a>
	       					</p>
	       			</div>
	       		</div>
	        	<div class="well well-small" style="background-color: rgb(40, 40, 40); border-radius: 6px 6px 6px 6px;">
				<div class="tabbable tabs-left">
				<% @all_comments = post.comment_threads %>
		        <% if @all_comments %>
		        	<ul class="nav nav-tabs">
		        		<% @i = 1 %>
						<% for c in @all_comments %>
							<li id="li-tab<%=@i%><%=@outer_index%>">
								<a href="#tab<%=@i%><%=@outer_index%>" data-toggle="tab"><i class="icon-comment icon-white"></i></a>
							</li>
					   		<% @i = @i + 1 %>
						<% end %>
					</ul>
					<div class="tab-content">
						<% @i = 1 %>
						<% for c in @all_comments %>							
					   		<% @user = find_user(c.user_id) %>
					   		<div class="tab-pane" id="tab<%=@i%><%=@outer_index%>">
					     	 <pre>
							    <p class="posted-details"><%= raw(c.body) %></p>
							    <p class="posted-at">–Posted  <abbr class="timeago" title="<%= (c.created_at).getutc.iso8601 %>"></abbr> by <a href="users/66354"><%= @user.username %> </a></p>
						     </pre>
							 <% @i = @i + 1 %>
							 <div class="pull-right"><% if admin_or_owner?(c.user_id) %>
						  		<i class="icon-edit icon-white"></i><%= link_to " Edit Comment", edit_comment_path(:id => c.id, :post_id => c.commentable_id) %> |
						  	 <% end %>
						  	 <% if admin_or_owner?(c.user_id) %>
						  		<i class="icon-trash icon-white"></i><%= link_to " Delete Comment", c , :params => {:id => c.id, :post_id => c.commentable_id}, :method =>:delete, :confirm => "Are you sure?" %>
						     <% end %></div>
					    	 
				     		</div>
					    	
						<% end %>
					</div>
			    <% end %>
			    </div> <!-- end of tabbable tabs-left --> 
			    </div> <!-- end of well small -->
			    <div><script language="javascript"> this.document.getElementById("li-tab1<%=@outer_index%>").setAttribute("class", "active");</script></div>
			    <div><script language="javascript"> this.document.getElementById("tab1<%=@outer_index%>").setAttribute("class", "tab-pane active");</script></div>
				
					
		  
		 <p>
		 <!-- <a href="/comments/new?post_id=<%= post.id %>" title="Comment" 
		   onclick="Modalbox.show(this.href, {title: this.title, width: 800}); return false;">
		   Comment</a> -->
		  <% if user_signed_in? %>
		     <i class="icon-pencil icon-white"></i><%= link_to " Comment on post", "/comments/new?post_id=#{post.id}"%> |
		  <% end %>
	 	  <% if admin_or_owner?(post.user_id) %>
		  	<i class="icon-edit icon-white"></i><%= link_to " Edit Post", edit_post_path(post) %> |
		  <% end %>
		  <% if admin_or_owner?(post.user_id) %>
		  	<i class="icon-trash icon-white"></i><%= link_to " Delete Post", post, :method =>:delete,:confirm => "Are you sure?" %>
		  <% end %>	
		 </p>
	 </div>	 <!-- end of well large -->	
     <%@outer_index = @outer_index + 1 %>	
	 <% end %>
	 
<br /><br />
<%= render :partial => "posts/tagcloud"  %>
<br /><br />